from __future__ import annotations

from manifest_tools import ROOT, merge_rows, read_jsonl, write_master


SEEDS = [
    {
        'source_platform': 'bilibili',
        'source_id': 'BV1m4u96dEen',
        'source_url': 'https://www.bilibili.com/video/BV1m4u96dEen/',
        'title': 'Evil直播录像：Evil当乘务员，Neuro你就开飞机吧（含多条2026长录播索引）',
        'uploader': 'public Bilibili uploader (to verify)',
        'discovery_method': 'public_web_search',
        'discovery_query': 'Neuro-sama Evil Neuro archive full VOD mirror download',
        'discovery_source': 'https://www.bilibili.com/video/BV1m4u96dEen/',
        'download_status': 'pending',
        'processing_status': 'pending',
        'participants': ['Neuro', 'Evil'],
        'language': 'zh-subtitle/en-source-unknown',
        'subtitle_languages': ['zh-Hans'],
        'rights_note': 'Public discovery lead; verify access, provenance, and source relationship before acquisition.',
    },
    {
        'source_platform': 'preservetube',
        'source_id': 'urtfm4ajjJk',
        'source_url': 'https://preservetube.com/watch?v=urtfm4ajjJk',
        'title': "Evil's 2026 Birthday Was a WILD Ride",
        'uploader': 'Neuro-sama / PreserveTube mirror index',
        'discovery_method': 'public_archive_search',
        'discovery_query': 'Neuro-sama Evil Neuro archive full VOD mirror download',
        'discovery_source': 'https://preservetube.com/channel/UCLHmLrj4pHHg3-iBJn_CqxA',
        'download_status': 'pending',
        'processing_status': 'pending',
        'participants': ['Neuro', 'Evil', 'Vedal', 'Mini', 'Cerber', 'Layna', 'Mimi', 'Crelly', 'Ellie', 'Chrchie', 'Koko', 'Camila'],
        'language': 'en',
        'subtitle_languages': [],
        'rights_note': 'Public archive page; clip/edited status and underlying source must be verified; training candidate false until context is recovered.',
        'training_candidate': False,
    },
    {
        'source_platform': 'preservetube',
        'source_id': '20lQ19HZrQM',
        'source_url': 'https://preservetube.com/watch?v=20lQ19HZrQM',
        'title': 'Evil Gets Chaotic With Cerber',
        'uploader': 'Neuro-sama / PreserveTube mirror index',
        'discovery_method': 'public_archive_search',
        'discovery_query': 'Neuro-sama Evil Neuro archive full VOD mirror download',
        'discovery_source': 'https://preservetube.com/channel/UCLHmLrj4pHHg3-iBJn_CqxA',
        'download_status': 'pending',
        'processing_status': 'pending',
        'participants': ['Evil', 'Cerber', 'Vedal'],
        'language': 'en',
        'subtitle_languages': [],
        'rights_note': 'Public archive page; likely edited clip, retain as source-recovery lead and do not use as high-weight training data without full context.',
        'training_candidate': False,
    },
    {
        'source_platform': 'preservetube',
        'source_id': 'muCljGPwlYo',
        'source_url': 'https://preservetube.com/watch?v=muCljGPwlYo',
        'title': 'Amazing NEW Upgrades For Neuro & Evil',
        'uploader': 'Neuro-sama / PreserveTube mirror index',
        'discovery_method': 'public_archive_search',
        'discovery_query': 'Neuro-sama Evil Neuro archive full VOD mirror download',
        'discovery_source': 'https://preservetube.com/channel/UCLHmLrj4pHHg3-iBJn_CqxA',
        'download_status': 'pending',
        'processing_status': 'pending',
        'participants': ['Neuro', 'Evil', 'Vedal'],
        'language': 'en',
        'subtitle_languages': [],
        'rights_note': 'Public archive page; likely edited clip, retain as source-recovery lead and do not use as high-weight training data without full context.',
        'training_candidate': False,
    },
    {
        'source_platform': 'bilibili',
        'source_id': 'BV1X6X9BuEyg',
        'source_url': 'https://www.bilibili.com/video/BV1X6X9BuEyg/',
        'title': 'Evil捉迷藏？！— Vedal和Neuro-sama',
        'uploader': 'Vedal和Neuro-sama',
        'discovery_method': 'public_web_search',
        'discovery_query': 'Neuro-sama Evil Neuro Bilibili 录播',
        'discovery_source': 'https://www.bilibili.com/list/3546729368520811/?bvid=BV1X6X9BuEyg',
        'download_status': 'pending',
        'processing_status': 'pending',
        'participants': ['Neuro', 'Evil', 'Vedal'],
        'language': 'zh-subtitle/en-source-unknown',
        'subtitle_languages': ['zh-Hans'],
        'rights_note': 'Public associated Bilibili lead; verify access and preserve uploader/source attribution.',
        'training_candidate': False,
    },
    {
        'source_platform': 'bilibili',
        'source_id': 'BV1AJ9UBVEaE',
        'source_url': 'https://www.bilibili.com/video/BV1AJ9UBVEaE/',
        'title': 'Neuro/Evil切片：19分带你看画！2026.4.29',
        'uploader': '西塞尔是只喵',
        'discovery_method': 'public_web_search',
        'discovery_query': 'Neuro-sama Evil Neuro Bilibili 字幕组',
        'discovery_source': 'https://www.bilibili.com/video/BV1AJ9UBVEaE/',
        'download_status': 'pending',
        'processing_status': 'pending',
        'participants': ['Neuro', 'Evil', 'Vedal'],
        'language': 'zh-subtitle/en-source-unknown',
        'subtitle_languages': ['zh-Hans'],
        'rights_note': 'Public subtitle clip lead; keep for source/context recovery, not high-weight training without original context.',
        'training_candidate': False,
    },
]


if __name__ == '__main__':
    write_master(merge_rows(read_jsonl(ROOT / 'manifest' / 'master_video_manifest.jsonl'), SEEDS))
    print(f'added_or_merged={len(SEEDS)}')
