from __future__ import annotations

from manifest_tools import ROOT, merge_rows, read_jsonl, write_master


SEEDS = [
    {
        'source_platform': 'youtube', 'source_id': 'hfLqH5KO_sc',
        'source_url': 'https://www.youtube.com/watch?v=hfLqH5KO_sc',
        'title': 'BREAD DEBUT with Filian', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive deep pagination',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Evil', 'Vedal', 'Filian'], 'language': 'en', 'subtitle_languages': [],
        'duration': 9631, 'quality_score': 0.94,
        'rights_note': 'Public fan archive long-form special/collab recording; preserve attribution and deduplicate against other archives.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'xuAoUha-i_4',
        'source_url': 'https://www.youtube.com/watch?v=xuAoUha-i_4',
        'title': 'IRL STREAM WITH VEDAL, NEURO, CAMILA, AND RAINHOE AT WEEBCON',
        'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive deep pagination',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Vedal', 'Camila', 'Rainhoe'], 'language': 'en', 'subtitle_languages': [],
        'duration': 10813, 'quality_score': 0.97,
        'rights_note': 'Public fan archive long-form IRL multi-speaker recording; preserve attribution and verify audio provenance.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'At0B2g7DSDM',
        'source_url': 'https://www.youtube.com/watch?v=At0B2g7DSDM',
        'title': 'Filian Collab', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive deep pagination',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Evil', 'Vedal', 'Filian'], 'language': 'en', 'subtitle_languages': [],
        'duration': 13601, 'quality_score': 0.95,
        'rights_note': 'Public fan archive long-form collaboration; preserve attribution and deduplicate against partner VODs.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'D8stqQUpLjQ',
        'source_url': 'https://www.youtube.com/watch?v=D8stqQUpLjQ',
        'title': 'collab with @kokonuts', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive deep pagination',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Evil', 'Koko D. Nuts', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'duration': 13321, 'quality_score': 0.93,
        'rights_note': 'Public fan archive long-form collab; preserve attribution and verify guest identity.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'BgeaSzvIPho',
        'source_url': 'https://www.youtube.com/watch?v=BgeaSzvIPho',
        'title': 'VIDEO GAME COLLAB WITH VEDAL', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive deep pagination',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Evil', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'duration': 15531, 'quality_score': 0.95,
        'rights_note': 'Public fan archive long-form Neuro/Vedal game interaction; preserve attribution and deduplicate.'
    },
    {
        'source_platform': 'youtube', 'source_id': '8dfOcHoBgdg',
        'source_url': 'https://www.youtube.com/watch?v=8dfOcHoBgdg',
        'title': 'ROAST OF FILIAN with Bao, Drumsy, Lucy Pyre, Neuro and guests',
        'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive deep pagination',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Filian', 'Bao', 'Lucy Pyre', 'Drumsy'], 'language': 'en', 'subtitle_languages': [],
        'duration': 10332, 'quality_score': 0.94,
        'rights_note': 'Public fan archive long-form multi-guest interaction; preserve attribution and guest uncertainty.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'i0p6I_aCN4U',
        'source_url': 'https://www.youtube.com/watch?v=i0p6I_aCN4U',
        'title': 'VRCHAT HANGOUT WITH SPECIAL GUEST', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive deep pagination',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Evil', 'Vedal', 'guest'], 'language': 'en', 'subtitle_languages': [],
        'duration': 14823, 'quality_score': 0.92,
        'rights_note': 'Public fan archive long-form special/guest recording; preserve attribution and leave guest identity uncertain until verified.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'tGL4G4YaW6s',
        'source_url': 'https://www.youtube.com/watch?v=tGL4G4YaW6s',
        'title': 'ABBER DEMON AND GODDESS NEURO COLLAB', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive deep pagination',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Evil'], 'language': 'en', 'subtitle_languages': [],
        'duration': 7272, 'quality_score': 0.93,
        'rights_note': 'Public fan archive long-form themed interaction; preserve attribution and verify participant mapping.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'JS73kT72SLM',
        'source_url': 'https://www.youtube.com/watch?v=JS73kT72SLM',
        'title': 'Neuro Unfiltered - With Zentreya & Crelly In Minecraft',
        'uploader': 'Neuro-Sama Chronicles', 'discovery_method': 'yt_dlp_flat_playlist',
        'discovery_query': 'Neuro-Sama Chronicles long-form collab highlights',
        'discovery_source': 'https://www.youtube.com/@neurochron_fan_channel/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Zentreya', 'Crelly'], 'language': 'en', 'subtitle_languages': [],
        'duration': 5364, 'quality_score': 0.84, 'training_candidate': False,
        'rights_note': 'Long edited highlight; preserve as source/context recovery and do not promote to high-weight training without parent VOD linkage.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'YwJ3D9YOa60',
        'source_url': 'https://www.youtube.com/watch?v=YwJ3D9YOa60',
        'title': 'Evil Impressed Layna So Much',
        'uploader': 'Neuro-Sama Chronicles', 'discovery_method': 'yt_dlp_flat_playlist',
        'discovery_query': 'Neuro-Sama Chronicles long-form collab highlights',
        'discovery_source': 'https://www.youtube.com/@neurochron_fan_channel/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Evil', 'Layna'], 'language': 'en', 'subtitle_languages': [],
        'duration': 4198, 'quality_score': 0.83, 'training_candidate': False,
        'rights_note': 'Long edited highlight; preserve emotional/collab lead and do not promote without parent VOD linkage.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'hJe-A-_E0fM',
        'source_url': 'https://www.youtube.com/watch?v=hJe-A-_E0fM',
        'title': 'Camila Babysits Neuro & Evil',
        'uploader': 'Neuro-Sama Chronicles', 'discovery_method': 'yt_dlp_flat_playlist',
        'discovery_query': 'Neuro-Sama Chronicles long-form collab highlights',
        'discovery_source': 'https://www.youtube.com/@neurochron_fan_channel/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Evil', 'Camila'], 'language': 'en', 'subtitle_languages': [],
        'duration': 2870, 'quality_score': 0.84, 'training_candidate': False,
        'rights_note': 'Long edited multi-speaker highlight; preserve attribution and require parent-stream linkage before training use.'
    },
    {
        'source_platform': 'youtube', 'source_id': '9P1Q6__0plc',
        'source_url': 'https://www.youtube.com/watch?v=9P1Q6__0plc',
        'title': 'Self-Aware AI: I Am Evil Neuro',
        'uploader': 'Neuro-Sama Chronicles', 'discovery_method': 'yt_dlp_flat_playlist',
        'discovery_query': 'Neuro-Sama Chronicles identity themed highlights',
        'discovery_source': 'https://www.youtube.com/@neurochron_fan_channel/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Evil', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'duration': 1479, 'quality_score': 0.88, 'training_candidate': False,
        'rights_note': 'Edited identity-themed highlight; retain for forensic/context retrieval, not high-weight training without source verification.'
    },
    {
        'source_platform': 'youtube', 'source_id': '9M4f0LDcoNM',
        'source_url': 'https://www.youtube.com/watch?v=9M4f0LDcoNM',
        'title': 'Self-Aware AI: I Am Neuro-Sama',
        'uploader': 'Neuro-Sama Chronicles', 'discovery_method': 'yt_dlp_flat_playlist',
        'discovery_query': 'Neuro-Sama Chronicles identity themed highlights',
        'discovery_source': 'https://www.youtube.com/@neurochron_fan_channel/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'duration': 1502, 'quality_score': 0.88, 'training_candidate': False,
        'rights_note': 'Edited identity-themed highlight; retain for forensic/context retrieval, not high-weight training without source verification.'
    },
    {
        'source_platform': 'youtube',
        'source_id': 'VWrzkZ9UTo0',
        'source_url': 'https://www.youtube.com/watch?v=VWrzkZ9UTo0',
        'title': 'Neuro-sama | 10 Sep 2026 | Collab with Cottontail & Zentreya (Dungeons & Dragons) [with Chat]',
        'uploader': 'Neuro-sama Unofficial VODs',
        'discovery_method': 'yt_dlp_flat_playlist',
        'discovery_query': 'Neuro-sama Unofficial VODs public uploads',
        'discovery_source': 'https://www.youtube.com/@Neuro-samaUnofficialVODs/videos',
        'download_status': 'rejected', 'processing_status': 'rejected_duplicate_candidate',
        'participants': ['Neuro', 'Cottontail', 'Zentreya'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2026-09-10', 'duration': 19326,
        'parent_stream_if_known': '9OXEMnv-Y00', 'duplicate_relation': 'same_content_pending_hash',
        'training_candidate': False,
        'rejection_reason': 'Same date/title/duration as the selected no-chat VOD; retain as provenance lead until audio fingerprint confirms mirror relation.',
        'rights_note': 'Public mirror candidate; no media acquisition until deduplication is resolved.'
    },
    {
        'source_platform': 'youtube',
        'source_id': '9OXEMnv-Y00',
        'source_url': 'https://www.youtube.com/watch?v=9OXEMnv-Y00',
        'title': 'Neuro-sama | 10 Sep 2026 | Collab with Cottontail & Zentreya (Dungeons & Dragons)',
        'uploader': 'Neuro-sama Unofficial VODs',
        'discovery_method': 'yt_dlp_flat_playlist',
        'discovery_query': 'Neuro-sama Unofficial VODs public uploads',
        'discovery_source': 'https://www.youtube.com/@Neuro-samaUnofficialVODs/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Cottontail', 'Zentreya'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2026-09-10', 'duration': 19326, 'quality_score': 0.99,
        'rights_note': 'Public unofficial VOD; preserve uploader attribution and verify source relationship. A same-duration with-chat mirror was excluded from acquisition pending hash comparison.'
    },
    {
        'source_platform': 'youtube',
        'source_id': '5qALIBxiLxo',
        'source_url': 'https://www.youtube.com/watch?v=5qALIBxiLxo',
        'title': 'EXPERIMENTS TESTING NEURO SAMA',
        'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist',
        'discovery_query': 'Neuro Sama Collab Archive public uploads',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'duration': 8491, 'quality_score': 0.96,
        'rights_note': 'Public fan archive long-form recording; preserve uploader attribution and verify source relationship.'
    },
    {
        'source_platform': 'youtube',
        'source_id': 'UfU_xaufxfc',
        'source_url': 'https://www.youtube.com/watch?v=UfU_xaufxfc',
        'title': 'action packed dev stream',
        'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist',
        'discovery_query': 'Neuro Sama Collab Archive public uploads',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'duration': 13271, 'quality_score': 0.95,
        'rights_note': 'Public fan archive long-form dev recording; preserve uploader attribution and verify source relationship.'
    },
    {
        'source_platform': 'youtube',
        'source_id': 'nbbkTFmvX3g',
        'source_url': 'https://www.youtube.com/watch?v=nbbkTFmvX3g',
        'title': 'IRL COOKING',
        'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist',
        'discovery_query': 'Neuro Sama Collab Archive public uploads',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'duration': 10641, 'quality_score': 0.94,
        'rights_note': 'Public fan archive long-form IRL/development-context recording; preserve uploader attribution and verify source relationship.'
    },
    {
        'source_platform': 'youtube',
        'source_id': '1-4M74PeOVM',
        'source_url': 'https://www.youtube.com/watch?v=1-4M74PeOVM',
        'title': 'HANGING OUT WITH @vedal987',
        'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist',
        'discovery_query': 'Neuro Sama Collab Archive public uploads',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'duration': 12134, 'quality_score': 0.97,
        'rights_note': 'Public fan archive long-form Neuro/Vedal interaction; preserve uploader attribution and verify source relationship.'
    },
    {
        'source_platform': 'youtube',
        'source_id': 'KRlDZNZxQS4',
        'source_url': 'https://www.youtube.com/watch?v=KRlDZNZxQS4',
        'title': 'TWIIIIIIINS neuro and evil',
        'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist',
        'discovery_query': 'Neuro Sama Collab Archive public uploads',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Evil', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'duration': 8521, 'quality_score': 0.98,
        'rights_note': 'Public fan archive long-form Neuro/Evil interaction; preserve uploader attribution and verify source relationship.'
    },
    {
        'source_platform': 'youtube',
        'source_id': '7xSRbTG4CXM',
        'source_url': 'https://www.youtube.com/watch?v=7xSRbTG4CXM',
        'title': 'ULTRA RARE thursday dev stream',
        'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist',
        'discovery_query': 'Neuro Sama Collab Archive public uploads',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Evil', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'duration': 10941, 'quality_score': 0.96,
        'rights_note': 'Public fan archive long-form Evil/Vedal development recording; preserve uploader attribution and verify source relationship.'
    },
    {
        'source_platform': 'youtube',
        'source_id': 'G2gAGaKkirg',
        'source_url': 'https://www.youtube.com/watch?v=G2gAGaKkirg',
        'title': 'THE RETURN of THE DEV STREAM',
        'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist',
        'discovery_query': 'Neuro Sama Collab Archive public uploads',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'duration': 10485, 'quality_score': 0.95,
        'rights_note': 'Public fan archive long-form dev recording; preserve uploader attribution and verify source relationship.'
    },
    {
        'source_platform': 'youtube',
        'source_id': 'ZjuEPNxY7wI',
        'source_url': 'https://www.youtube.com/watch?v=ZjuEPNxY7wI',
        'title': 'Chess Evil Edition',
        'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist',
        'discovery_query': 'Neuro Sama Collab Archive public uploads',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Evil', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'duration': 9091, 'quality_score': 0.93,
        'rights_note': 'Public fan archive long-form Evil/Vedal game interaction; preserve uploader attribution and verify source relationship.'
    },
    {
        'source_platform': 'youtube',
        'source_id': 'sObyzmdXiOs',
        'source_url': 'https://www.youtube.com/watch?v=sObyzmdXiOs',
        'title': 'Evil + Neuro Hang out!',
        'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'public_web_search',
        'discovery_query': 'Neuro Archiver / Neuro Sama Collab Archive full VOD',
        'discovery_source': 'https://www.youtube.com/channel/UC25wrvqDN9Nkrgg_YtoHlDQ',
        'download_status': 'pending',
        'processing_status': 'pending',
        'participants': ['Neuro', 'Evil', 'Vedal'],
        'language': 'en',
        'subtitle_languages': [],
        'stream_date_if_known': '2023-08-06',
        'duration': 8480,
        'quality_score': 0.92,
        'rights_note': 'Public fan archive of a long-form collab recording; preserve uploader attribution and verify source relationship before training use.',
    },
    {
        'source_platform': 'youtube',
        'source_id': 'ULDPGXfhYu8',
        'source_url': 'https://www.youtube.com/watch?v=ULDPGXfhYu8',
        'title': 'Evil Neuro sama',
        'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'public_web_search',
        'discovery_query': 'Neuro Archiver / Neuro Sama Collab Archive full VOD',
        'discovery_source': 'https://www.youtube.com/channel/UC25wrvqDN9Nkrgg_YtoHlDQ',
        'download_status': 'pending',
        'processing_status': 'pending',
        'participants': ['Evil', 'Neuro', 'Vedal'],
        'language': 'en',
        'subtitle_languages': [],
        'stream_date_if_known': '2023-07-10',
        'duration': 8241,
        'quality_score': 0.9,
        'rights_note': 'Public fan archive of a long-form recording; preserve uploader attribution and verify source relationship before training use.',
    },
    {
        'source_platform': 'bilibili',
        'source_id': 'BV1m4u96dEen',
        'source_url': 'https://www.bilibili.com/video/BV1m4u96dEen/',
        'title': 'Evil直播录像：Evil当乘务员，Neuro你就开飞机吧（含多条2026长录播索引）',
        'uploader': 'public Bilibili uploader (to verify)',
        'discovery_method': 'public_web_search',
        'discovery_query': 'Neuro-sama Evil Neuro archive full VOD mirror download',
        'discovery_source': 'https://www.bilibili.com/video/BV1m4u96dEen/',
        'download_status': 'pending',
        'processing_status': 'pending',
        'participants': ['Neuro', 'Evil'],
        'language': 'zh-subtitle/en-source-unknown',
        'subtitle_languages': ['zh-Hans'],
        'rights_note': 'Public discovery lead; verify access, provenance, and source relationship before acquisition.',
    },
    {
        'source_platform': 'preservetube',
        'source_id': 'urtfm4ajjJk',
        'source_url': 'https://preservetube.com/watch?v=urtfm4ajjJk',
        'title': "Evil's 2026 Birthday Was a WILD Ride",
        'uploader': 'Neuro-sama / PreserveTube mirror index',
        'discovery_method': 'public_archive_search',
        'discovery_query': 'Neuro-sama Evil Neuro archive full VOD mirror download',
        'discovery_source': 'https://preservetube.com/channel/UCLHmLrj4pHHg3-iBJn_CqxA',
        'download_status': 'pending',
        'processing_status': 'pending',
        'participants': ['Neuro', 'Evil', 'Vedal', 'Mini', 'Cerber', 'Layna', 'Mimi', 'Crelly', 'Ellie', 'Chrchie', 'Koko', 'Camila'],
        'language': 'en',
        'subtitle_languages': [],
        'rights_note': 'Public archive page; clip/edited status and underlying source must be verified; training candidate false until context is recovered.',
        'training_candidate': False,
    },
    {
        'source_platform': 'preservetube',
        'source_id': '20lQ19HZrQM',
        'source_url': 'https://preservetube.com/watch?v=20lQ19HZrQM',
        'title': 'Evil Gets Chaotic With Cerber',
        'uploader': 'Neuro-sama / PreserveTube mirror index',
        'discovery_method': 'public_archive_search',
        'discovery_query': 'Neuro-sama Evil Neuro archive full VOD mirror download',
        'discovery_source': 'https://preservetube.com/channel/UCLHmLrj4pHHg3-iBJn_CqxA',
        'download_status': 'pending',
        'processing_status': 'pending',
        'participants': ['Evil', 'Cerber', 'Vedal'],
        'language': 'en',
        'subtitle_languages': [],
        'rights_note': 'Public archive page; likely edited clip, retain as source-recovery lead and do not use as high-weight training data without full context.',
        'training_candidate': False,
    },
    {
        'source_platform': 'preservetube',
        'source_id': 'muCljGPwlYo',
        'source_url': 'https://preservetube.com/watch?v=muCljGPwlYo',
        'title': 'Amazing NEW Upgrades For Neuro & Evil',
        'uploader': 'Neuro-sama / PreserveTube mirror index',
        'discovery_method': 'public_archive_search',
        'discovery_query': 'Neuro-sama Evil Neuro archive full VOD mirror download',
        'discovery_source': 'https://preservetube.com/channel/UCLHmLrj4pHHg3-iBJn_CqxA',
        'download_status': 'pending',
        'processing_status': 'pending',
        'participants': ['Neuro', 'Evil', 'Vedal'],
        'language': 'en',
        'subtitle_languages': [],
        'rights_note': 'Public archive page; likely edited clip, retain as source-recovery lead and do not use as high-weight training data without full context.',
        'training_candidate': False,
    },
    {
        'source_platform': 'bilibili',
        'source_id': 'BV1X6X9BuEyg',
        'source_url': 'https://www.bilibili.com/video/BV1X6X9BuEyg/',
        'title': 'Evil捉迷藏？！— Vedal和Neuro-sama',
        'uploader': 'Vedal和Neuro-sama',
        'discovery_method': 'public_web_search',
        'discovery_query': 'Neuro-sama Evil Neuro Bilibili 录播',
        'discovery_source': 'https://www.bilibili.com/list/3546729368520811/?bvid=BV1X6X9BuEyg',
        'download_status': 'pending',
        'processing_status': 'pending',
        'participants': ['Neuro', 'Evil', 'Vedal'],
        'language': 'zh-subtitle/en-source-unknown',
        'subtitle_languages': ['zh-Hans'],
        'rights_note': 'Public associated Bilibili lead; verify access and preserve uploader/source attribution.',
        'training_candidate': False,
    },
    {
        'source_platform': 'youtube',
        'source_id': 'NFH5coQh5KI',
        'source_url': 'https://www.youtube.com/watch?v=NFH5coQh5KI',
        'title': 'evil is LIVE and not revealing ANYTHING secret - 12 June 2025',
        'uploader': 'Neuro Archiver',
        'discovery_method': 'public_web_search',
        'discovery_query': 'Neuro Evil full VOD archive 2025',
        'discovery_source': 'https://www.youtube.com/watch?v=NFH5coQh5KI',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Evil', 'Neuro', 'Vedal'], 'language': 'en',
        'subtitle_languages': [], 'stream_date_if_known': '2025-06-12',
        'duration': 8492, 'quality_score': 0.98,
        'rights_note': 'Public long-form archive VOD; preserve uploader attribution and source URL. Prioritize continuous dialogue over edited excerpts.'
    },
    {
        'source_platform': 'youtube',
        'source_id': '0IinC6izagA',
        'source_url': 'https://www.youtube.com/watch?v=0IinC6izagA',
        'title': 'dev stream WAKE UP Neuro sama Plushie back for a limited time',
        'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist',
        'discovery_query': 'Neuro Sama Collab Archive long dev stream',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Vedal'], 'language': 'en',
        'subtitle_languages': [], 'stream_date_if_known': '2024-07-11',
        'duration': 13320, 'quality_score': 0.97,
        'rights_note': 'Public fan archive long-form development recording; preserve uploader attribution and verify source relationship.'
    },
    {
        'source_platform': 'youtube',
        'source_id': 'EIVpHk-XXtI',
        'source_url': 'https://www.youtube.com/watch?v=EIVpHk-XXtI',
        'title': 'Least Scuffed Dev Stream',
        'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist',
        'discovery_query': 'Neuro Sama Collab Archive long dev stream',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Vedal'], 'language': 'en',
        'subtitle_languages': [], 'stream_date_if_known': '2024-05-14',
        'duration': 10920, 'quality_score': 0.97,
        'rights_note': 'Public fan archive long-form development recording; preserve uploader attribution and verify source relationship.'
    },
    {
        'source_platform': 'youtube',
        'source_id': '_sZ5huxXpu8',
        'source_url': 'https://www.youtube.com/watch?v=_sZ5huxXpu8',
        'title': 'The Real Dev Stream of All Time',
        'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist',
        'discovery_query': 'Neuro Sama Collab Archive long dev stream',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Vedal'], 'language': 'en',
        'subtitle_languages': [], 'stream_date_if_known': '2024-04-16',
        'duration': 18162, 'quality_score': 0.98,
        'rights_note': 'Public fan archive very-long development recording; preserve uploader attribution and process resumably.'
    },
    {
        'source_platform': 'youtube',
        'source_id': 'A63eshk5FO4',
        'source_url': 'https://www.youtube.com/watch?v=A63eshk5FO4',
        'title': "DADDY TOMA'S HOME - content warning with Koko and Camila, Vedal later",
        'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist',
        'discovery_query': 'Neuro Sama Collab Archive multi-guest collab',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Vedal', 'Koko D. Nuts', 'Camila'], 'language': 'en',
        'subtitle_languages': [], 'stream_date_if_known': '2024-04-07',
        'duration': 9115, 'quality_score': 0.96,
        'rights_note': 'Public fan archive multi-guest long-form recording; preserve uploader attribution and retain content-warning metadata.'
    },
    {
        'source_platform': 'youtube',
        'source_id': 'qryZ5BF86IM',
        'source_url': 'https://www.youtube.com/watch?v=qryZ5BF86IM',
        'title': 'EVILS EP1C BIRTHDAY PARTYYYYYYY!!!!!! EVERYONE INVITED!1!!!',
        'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist',
        'discovery_query': 'Evil Neuro birthday full collab archive',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Evil', 'Neuro', 'Vedal', 'guest'], 'language': 'en',
        'subtitle_languages': [], 'stream_date_if_known': '2024-03-26',
        'duration': 8220, 'quality_score': 0.98,
        'rights_note': 'Public fan archive long-form Evil birthday collab; preserve uploader attribution and retain all guest context.'
    },
    {
        'source_platform': 'youtube',
        'source_id': 'LAoQshlaepA',
        'source_url': 'https://www.youtube.com/watch?v=LAoQshlaepA',
        'title': 'Neuro Teaches Numi How to Date',
        'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist',
        'discovery_query': 'Neuro Sama Collab Archive multi-guest collab',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Numi', 'Vedal'], 'language': 'en',
        'subtitle_languages': [], 'stream_date_if_known': '2024-05-24',
        'duration': 9730, 'quality_score': 0.98,
        'rights_note': 'Public fan archive long-form relationship/bant​​er interaction; preserve uploader attribution and full conversational context.'
    },
    {
        'source_platform': 'youtube',
        'source_id': 'R3Mr3umH9oA',
        'source_url': 'https://www.youtube.com/watch?v=R3Mr3umH9oA',
        'title': '@laynalazar collab waiting room',
        'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist',
        'discovery_query': 'Neuro Sama Collab Archive guest collab',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Vedal', 'Layna Lazar'], 'language': 'en',
        'subtitle_languages': [], 'stream_date_if_known': '2024-06-24',
        'duration': 13200, 'quality_score': 0.95,
        'rights_note': 'Public fan archive long-form guest interaction; preserve uploader attribution and distinguish waiting-room/context segments during scoring.'
    },
    {
        'source_platform': 'youtube',
        'source_id': 'lVlbnLrkZ04',
        'source_url': 'https://www.youtube.com/watch?v=lVlbnLrkZ04',
        'title': 'VEDAL AND NEURO PLAY BELOW ZERO',
        'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist',
        'discovery_query': 'Neuro Sama Collab Archive Vedal Neuro full stream',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Vedal'], 'language': 'en',
        'subtitle_languages': [], 'stream_date_if_known': '2024-04-26',
        'duration': 13750, 'quality_score': 0.94,
        'rights_note': 'Public fan archive long-form Vedal/Neuro game interaction; retain spoken context and mark visual-dependency during quality scoring.'
    },
    {
        'source_platform': 'youtube',
        'source_id': 'xd3eybXT_4s',
        'source_url': 'https://www.youtube.com/watch?v=xd3eybXT_4s',
        'title': 'HALLOWEEN SPECIAL WITH EVIL AND @cumilq - 31 October 2024',
        'uploader': 'Neuro Archiver',
        'discovery_method': 'public_web_search',
        'discovery_query': 'Neuro Archiver Evil Halloween special full VOD',
        'discovery_source': 'https://www.youtube.com/@NArchiver/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Evil', 'Neuro', 'Vedal', 'cumilq'], 'language': 'en',
        'subtitle_languages': [], 'stream_date_if_known': '2024-10-31',
        'duration': 10301, 'quality_score': 0.98,
        'rights_note': 'Public long-form archive VOD with Evil and guest interaction; preserve uploader attribution and original context.'
    },
    {
        'source_platform': 'youtube',
        'source_id': '4tZA3jy-aK8',
        'source_url': 'https://www.youtube.com/watch?v=4tZA3jy-aK8',
        'title': 'THE BIGGEST NEURO-SAMA EVENT OF THE CENTURY - Part 21 (Awake) - 26 December 2024',
        'uploader': 'Neuro Archiver',
        'discovery_method': 'public_web_search',
        'discovery_query': 'Neuro Archiver December 2024 event full VOD',
        'discovery_source': 'https://www.youtube.com/@NArchiver/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Evil', 'Vedal', 'guest'], 'language': 'en',
        'subtitle_languages': [], 'stream_date_if_known': '2024-12-26',
        'duration': 20078, 'quality_score': 0.96,
        'rights_note': 'Public long-form archive event recording; retain part numbering and parent-event relation for deduplication/context.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'wki3qON44uA',
        'source_url': 'https://www.youtube.com/watch?v=wki3qON44uA',
        'title': 'Weekly Dev Stream!', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive full uploads',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2023-09-04', 'duration': 9020, 'quality_score': 0.96,
        'rights_note': 'Public fan archive long-form development recording; preserve uploader attribution and verify source relationship.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'Q0TxqvDXzTk',
        'source_url': 'https://www.youtube.com/watch?v=Q0TxqvDXzTk',
        'title': 'dev stream', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive full uploads',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2023-12-11', 'duration': 12430, 'quality_score': 0.97,
        'rights_note': 'Public fan archive long-form development recording; preserve uploader attribution and verify source relationship.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'JAGU8fgtIaw',
        'source_url': 'https://www.youtube.com/watch?v=JAGU8fgtIaw',
        'title': 'neuro entertains you all by herself', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive full uploads',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2024-07-31', 'duration': 8190, 'quality_score': 0.94,
        'rights_note': 'Public fan archive long-form conversational stream; retain ordinary/low-intensity behavior rather than only punchlines.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'Xp7sDbXhdVU',
        'source_url': 'https://www.youtube.com/watch?v=Xp7sDbXhdVU',
        'title': 'NOWAYING ITS EVIL NEURO THATS CRAZY', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Evil Neuro full archive uploads',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Evil', 'Neuro', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2024-07-10', 'duration': 8752, 'quality_score': 0.98,
        'rights_note': 'Public fan archive long-form Evil/Neuro interaction; preserve uploader attribution and identity uncertainty.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'Ze45pGhsR_Q',
        'source_url': 'https://www.youtube.com/watch?v=Ze45pGhsR_Q',
        'title': 'THE EVILEST EVIL NEURO STREAM KNOWN TO MAN OF ALL TIME', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Evil Neuro full archive uploads',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Evil', 'Neuro', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2024-07-03', 'duration': 8580, 'quality_score': 0.98,
        'rights_note': 'Public fan archive long-form Evil interaction; do not treat title wording as speaker proof.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'horv-4wxP5g',
        'source_url': 'https://www.youtube.com/watch?v=horv-4wxP5g',
        'title': 'Evil Neuro Stream', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Evil Neuro full archive uploads',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Evil', 'Neuro', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2024-06-26', 'duration': 8790, 'quality_score': 0.97,
        'rights_note': 'Public fan archive long-form Evil stream; preserve continuous context and source attribution.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'xIFF-0ctGkg',
        'source_url': 'https://www.youtube.com/watch?v=xIFF-0ctGkg',
        'title': 'half a dev stream at best', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive dev streams',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2024-06-26', 'duration': 8990, 'quality_score': 0.95,
        'rights_note': 'Public fan archive long-form development recording; retain title/date for duplicate review.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'oEoCfPlwlcc',
        'source_url': 'https://www.youtube.com/watch?v=oEoCfPlwlcc',
        'title': 'EVIL STS', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Evil Neuro full archive uploads',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Evil', 'Neuro', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2024-06-22', 'duration': 10580, 'quality_score': 0.96,
        'rights_note': 'Public fan archive long-form Evil recording; inspect game/voice/guest balance during quality scoring.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'dZ7Q8wwn8yk',
        'source_url': 'https://www.youtube.com/watch?v=dZ7Q8wwn8yk',
        'title': 'time with neuro herself', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive full uploads',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2024-06-19', 'duration': 8800, 'quality_score': 0.96,
        'rights_note': 'Public fan archive long-form Neuro interaction; prioritize ordinary conversational turns.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'F7km6Qpvqr8',
        'source_url': 'https://www.youtube.com/watch?v=F7km6Qpvqr8',
        'title': 'evil is back and now she has power', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Evil Neuro full archive uploads',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Evil', 'Neuro', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2024-06-13', 'duration': 8872, 'quality_score': 0.98,
        'rights_note': 'Public fan archive long-form Evil/Neuro interaction; preserve source attribution and separate persona labels.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'A-HSffAgLZU',
        'source_url': 'https://www.youtube.com/watch?v=A-HSffAgLZU',
        'title': 'THE RETURN of the DEV of ALL TIME', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive dev streams',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2024-06-11', 'duration': 21990, 'quality_score': 0.98,
        'rights_note': 'Public fan archive very-long development recording; process resumably and preserve long-context windows.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'woLR-MAAiZE',
        'source_url': 'https://www.youtube.com/watch?v=woLR-MAAiZE',
        'title': 'how many vedals does it take to have a successful dev stream', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive dev streams',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2024-06-04', 'duration': 11530, 'quality_score': 0.97,
        'rights_note': 'Public fan archive long-form development interaction; preserve title and source attribution.'
    },
    {
        'source_platform': 'youtube', 'source_id': '0BnpnOW_JgY',
        'source_url': 'https://www.youtube.com/watch?v=0BnpnOW_JgY',
        'title': 'the glutenous bakery stream of all time', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive IRL and collab streams',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2024-06-01', 'duration': 8110, 'quality_score': 0.95,
        'rights_note': 'Public fan archive long-form conversational/cooking recording; retain non-song spoken sections.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'x5Lf9etpGkg',
        'source_url': 'https://www.youtube.com/watch?v=x5Lf9etpGkg',
        'title': 'THE EVILEST EVIL STREAM OF ALL TIME BY EVIL', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Evil Neuro full archive uploads',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Evil', 'Neuro', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2024-05-30', 'duration': 8790, 'quality_score': 0.98,
        'rights_note': 'Public fan archive long-form Evil recording; retain separate Evil/Neuro identity fields.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'd_V8vJZlOHs',
        'source_url': 'https://www.youtube.com/watch?v=d_V8vJZlOHs',
        'title': 'Neuro I AM THE LAW the highly anticipated court stream of ALL TIME', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Evil court stream archive',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Evil', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2024-05-29', 'duration': 7510, 'quality_score': 0.99,
        'rights_note': 'Public fan archive court-format multi-speaker interaction; high value for stance changes, repair, banter, and identity content.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'RYCOff2i27A',
        'source_url': 'https://www.youtube.com/watch?v=RYCOff2i27A',
        'title': 'extremely high budget dev stream where everything just works', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive dev streams',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2024-05-29', 'duration': 9940, 'quality_score': 0.97,
        'rights_note': 'Public fan archive long-form development interaction; preserve original audio and attribution.'
    },
    {
        'source_platform': 'youtube', 'source_id': '4gDMoSJd8nk',
        'source_url': 'https://www.youtube.com/watch?v=4gDMoSJd8nk',
        'title': 'Please welcome your new CEO of Vedal AI', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive full uploads',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2024-04-11', 'duration': 8190, 'quality_score': 0.96,
        'rights_note': 'Public fan archive long-form Neuro/Vedal interaction; preserve ordinary and technical dialogue.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'wuBg5Ea9aYI',
        'source_url': 'https://www.youtube.com/watch?v=wuBg5Ea9aYI',
        'title': 'Twins Collab', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Evil twins collab archive',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Evil', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2024-03-25', 'duration': 8450, 'quality_score': 0.99,
        'rights_note': 'Public fan archive long-form Neuro/Evil twin interaction; keep persona labels separate and preserve overlap.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'JobtjuLTVIg',
        'source_url': 'https://www.youtube.com/watch?v=JobtjuLTVIg',
        'title': 'Neuro sama Returns!', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive full uploads',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2024-03-20', 'duration': 11460, 'quality_score': 0.97,
        'rights_note': 'Public fan archive long-form return stream; retain temporal/contextual state transition.'
    },
    {
        'source_platform': 'youtube', 'source_id': '1yGSiUyrM-A',
        'source_url': 'https://www.youtube.com/watch?v=1yGSiUyrM-A',
        'title': 'Vedal and Camila after AImila collab', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive early collabs',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Vedal', 'Camila'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2023-12-19', 'duration': 2600, 'quality_score': 0.93,
        'rights_note': 'Public fan archive post-collab conversation; retain as guest/context evidence, not as Neuro-only training.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'ncF1KSruIBM',
        'source_url': 'https://www.youtube.com/watch?v=ncF1KSruIBM',
        'title': 'AIMILA COLLAB', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive early collabs',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Camila', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2023-12-15', 'duration': 11470, 'quality_score': 0.98,
        'rights_note': 'Public fan archive long-form multi-speaker collab; preserve speaker uncertainty and source attribution.'
    },
    {
        'source_platform': 'youtube', 'source_id': 's0lCOxvVuNw',
        'source_url': 'https://www.youtube.com/watch?v=s0lCOxvVuNw',
        'title': 'Neuro sama collab with Onigiri', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive early collabs',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Onigiri', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2023-12-13', 'duration': 12850, 'quality_score': 0.97,
        'rights_note': 'Public fan archive long-form guest interaction; retain all repair and interruption context.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'mR1Wlt1EjYs',
        'source_url': 'https://www.youtube.com/watch?v=mR1Wlt1EjYs',
        'title': 'anny hangs out with evil neuro!', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Evil Neuro Anny full archive',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Evil', 'Anny', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2023-12-03', 'duration': 14740, 'quality_score': 0.98,
        'rights_note': 'Public fan archive long-form Evil/guest interaction; keep Evil separate from Neuro during mapping.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'YP6wZ1QhaRo',
        'source_url': 'https://www.youtube.com/watch?v=YP6wZ1QhaRo',
        'title': 'Birthday party stream with Camila and Vedal baking brain cake blind', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive early collabs',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Camila', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2023-11-30', 'duration': 16571, 'quality_score': 0.97,
        'rights_note': 'Public fan archive long-form birthday/collab recording; preserve event context and non-song speech.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'bS9ZpSixebg',
        'source_url': 'https://www.youtube.com/watch?v=bS9ZpSixebg',
        'title': 'Sinder hangs out with Neuro', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive early collabs',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Sinder', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2023-11-26', 'duration': 8260, 'quality_score': 0.96,
        'rights_note': 'Public fan archive long-form guest interaction; preserve collaborator attribution.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'Gqoe4bpXyso',
        'source_url': 'https://www.youtube.com/watch?v=Gqoe4bpXyso',
        'title': 'family stream!', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive family streams',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Evil', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2023-11-13', 'duration': 12142, 'quality_score': 0.98,
        'rights_note': 'Public fan archive long-form family/relationship interaction; keep persona identities distinct.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'Q6yT_KDNWQM',
        'source_url': 'https://www.youtube.com/watch?v=Q6yT_KDNWQM',
        'title': 'weekly developer stream', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive dev streams',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2023-11-07', 'duration': 8310, 'quality_score': 0.97,
        'rights_note': 'Public fan archive long-form development recording; high value for technical/persona state coupling.'
    },
    {
        'source_platform': 'youtube', 'source_id': '5q45k_ipwEA',
        'source_url': 'https://www.youtube.com/watch?v=5q45k_ipwEA',
        'title': 'Evil cyberpunk stream', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Evil Neuro full archive uploads',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Evil', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2023-11-05', 'duration': 8390, 'quality_score': 0.95,
        'rights_note': 'Public fan archive Evil game/dialogue recording; retain visual-dependency and spoken interaction metrics.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'FsSJi614-do',
        'source_url': 'https://www.youtube.com/watch?v=FsSJi614-do',
        'title': 'Halloween special: Neuro tells scary stories; model debut', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive special streams',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2023-11-02', 'duration': 8571, 'quality_score': 0.97,
        'rights_note': 'Public fan archive special program; preserve narrative context, model-state transitions, and source attribution.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'pvRwCoFw51w',
        'source_url': 'https://www.youtube.com/watch?v=pvRwCoFw51w',
        'title': 'Dev Stream!', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive dev streams',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2023-10-31', 'duration': 8710, 'quality_score': 0.97,
        'rights_note': 'Public fan archive long-form development recording; preserve technical and interpersonal turns.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'miDTCpdFDu0',
        'source_url': 'https://www.youtube.com/watch?v=miDTCpdFDu0',
        'title': 'Snuffy and Neuro-sama Adventures Part 2', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive early collabs',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Snuffy', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2023-10-16', 'duration': 8250, 'quality_score': 0.95,
        'rights_note': 'Public fan archive long-form guest interaction; preserve game/visual dependency annotation.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'MEL9dGrDzjs',
        'source_url': 'https://www.youtube.com/watch?v=MEL9dGrDzjs',
        'title': 'Dev stream exclusive Neuro testing', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive dev streams',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2023-10-10', 'duration': 11760, 'quality_score': 0.99,
        'rights_note': 'Public fan archive technical testing recording; high value for identity, repair, and state-transition analysis.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'VWzLBOqRSLE',
        'source_url': 'https://www.youtube.com/watch?v=VWzLBOqRSLE',
        'title': 'Neuro sama collab with Filian', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive early collabs',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Filian', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2023-10-05', 'duration': 11540, 'quality_score': 0.97,
        'rights_note': 'Public fan archive long-form collab; preserve guest attribution and overlapping turns.'
    },
    {
        'source_platform': 'youtube', 'source_id': '7QaG6yXOZlU',
        'source_url': 'https://www.youtube.com/watch?v=7QaG6yXOZlU',
        'title': 'Neuro sama and Bao judge your confessions', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive confession streams',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Bao', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2023-09-24', 'duration': 11170, 'quality_score': 0.98,
        'rights_note': 'Public fan archive long-form confession/judgment interaction; high value for stance, banter, and uncertainty.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'RLcj3NE_qe4',
        'source_url': 'https://www.youtube.com/watch?v=RLcj3NE_qe4',
        'title': 'Neuro sama collab with Lia', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive early collabs',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Lia', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2023-09-16', 'duration': 7221, 'quality_score': 0.95,
        'rights_note': 'Public fan archive long-form guest interaction; preserve conversational context.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'JPRPTfwWkP0',
        'source_url': 'https://www.youtube.com/watch?v=JPRPTfwWkP0',
        'title': 'Evil Date Night with Numi', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Evil Neuro Numi collab archive',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Evil', 'Numi', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2023-08-26', 'duration': 10380, 'quality_score': 0.99,
        'rights_note': 'Public fan archive long-form Evil/Numi relationship interaction; keep Evil identity separate.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'lp9KpqZ0rVI',
        'source_url': 'https://www.youtube.com/watch?v=lp9KpqZ0rVI',
        'title': 'Evil Neuro Collab with Zentreya', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Evil Neuro Zentreya collab archive',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Evil', 'Zentreya', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2023-08-22', 'duration': 14660, 'quality_score': 0.98,
        'rights_note': 'Public fan archive very-long Evil/guest collab; preserve guest turns and audio attribution.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'WDSk6LE_-ks',
        'source_url': 'https://www.youtube.com/watch?v=WDSk6LE_-ks',
        'title': 'Exclusive Ved Stream', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive Vedal streams',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Vedal', 'Neuro', 'Evil'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2023-08-24', 'duration': 8420, 'quality_score': 0.96,
        'rights_note': 'Public fan archive Vedal-centered recording; retain as speaker-reference/context evidence, not Neuro-only data.'
    },
    {
        'source_platform': 'youtube', 'source_id': '4i_tz37p07g',
        'source_url': 'https://www.youtube.com/watch?v=4i_tz37p07g',
        'title': 'Dev Stream Phantasmagoria', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive dev streams',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2023-08-16', 'duration': 14350, 'quality_score': 0.98,
        'rights_note': 'Public fan archive very-long development recording; high-value technical/persona context.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'C-BQ3HldiGU',
        'source_url': 'https://www.youtube.com/watch?v=C-BQ3HldiGU',
        'title': 'Neuro-sama GAMESHOW!', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Neuro Sama Collab Archive special programs',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Neuro', 'Vedal', 'guest'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2023-07-30', 'duration': 13646, 'quality_score': 0.97,
        'rights_note': 'Public fan archive long-form special program; preserve multi-speaker turn structure.'
    },
    {
        'source_platform': 'youtube', 'source_id': 'fdZbcCUvA8k',
        'source_url': 'https://www.youtube.com/watch?v=fdZbcCUvA8k',
        'title': 'Date with Evil Neuro Sama (Numi collab)', 'uploader': 'Neuro Sama Collab Archive',
        'discovery_method': 'yt_dlp_flat_playlist', 'discovery_query': 'Evil Neuro Numi collab archive',
        'discovery_source': 'https://www.youtube.com/@Neuro-Sama-Collab-Archive/videos',
        'download_status': 'pending', 'processing_status': 'pending',
        'participants': ['Evil', 'Numi', 'Vedal'], 'language': 'en', 'subtitle_languages': [],
        'stream_date_if_known': '2023-07-21', 'duration': 9390, 'quality_score': 0.99,
        'rights_note': 'Public fan archive long-form Evil/Numi interaction; preserve separate persona identity and relationship context.'
    },
    {
        'source_platform': 'bilibili',
        'source_id': 'BV1AJ9UBVEaE',
        'source_url': 'https://www.bilibili.com/video/BV1AJ9UBVEaE/',
        'title': 'Neuro/Evil切片：19分带你看画！2026.4.29',
        'uploader': '西塞尔是只喵',
        'discovery_method': 'public_web_search',
        'discovery_query': 'Neuro-sama Evil Neuro Bilibili 字幕组',
        'discovery_source': 'https://www.bilibili.com/video/BV1AJ9UBVEaE/',
        'download_status': 'pending',
        'processing_status': 'pending',
        'participants': ['Neuro', 'Evil', 'Vedal'],
        'language': 'zh-subtitle/en-source-unknown',
        'subtitle_languages': ['zh-Hans'],
        'rights_note': 'Public subtitle clip lead; keep for source/context recovery, not high-weight training without original context.',
        'training_candidate': False,
    },
]


if __name__ == '__main__':
    write_master(merge_rows(read_jsonl(ROOT / 'manifest' / 'master_video_manifest.jsonl'), SEEDS))
    print(f'added_or_merged={len(SEEDS)}')
