from __future__ import annotations

import json
from pathlib import Path

from manifest_tools import ROOT, merge_rows, read_jsonl, write_master


LEADS = [
    {
        "source_platform": "youtube",
        "source_id": "i4VSpJK8gTs",
        "source_url": "https://www.youtube.com/watch?v=i4VSpJK8gTs",
        "title": "ultra rare evil dev stream - 13 July 2026",
        "uploader": "Neuro Archiver",
        "discovery_method": "public_web_search",
        "discovery_query": "Neuro Archiver evil dev stream July 2026",
        "discovery_source": "https://www.youtube.com/@NArchiver",
        "stream_date_if_known": "13 Jul 2026",
        "participants": ["Evil", "Vedal"],
        "language": "en",
        "subtitle_languages": [],
        "download_status": "pending",
        "processing_status": "pending",
        "rights_note": "Public fan archive lead; retain uploader attribution and verify source relationship before acquisition.",
    },
    {
        "source_platform": "youtube",
        "source_id": "Ak7mzd3L7b0",
        "source_url": "https://www.youtube.com/watch?v=Ak7mzd3L7b0",
        "title": "The Evil Neuro Dev Stream of All Time - 31 July 2023",
        "uploader": "Neuro Archiver",
        "discovery_method": "public_web_search",
        "discovery_query": "Neuro Archiver Evil Neuro dev stream 31 July 2023",
        "discovery_source": "https://www.youtube.com/@NArchiver",
        "stream_date_if_known": "31 Jul 2023",
        "participants": ["Evil", "Vedal"],
        "language": "en",
        "subtitle_languages": [],
        "download_status": "pending",
        "processing_status": "pending",
        "rights_note": "Public fan archive lead; preserve original-audio claim as provenance metadata, not as verified fact.",
    },
    {
        "source_platform": "youtube",
        "source_id": "hxOO4D8pQQA",
        "source_url": "https://www.youtube.com/watch?v=hxOO4D8pQQA",
        "title": "NEURO-SAMA RETURNS TO OSU - 27 July 2025",
        "uploader": "Neuro Archiver",
        "discovery_method": "public_archive_search",
        "discovery_query": "Neuro Archiver Neuro-sama full VOD July 2025 OSU",
        "discovery_source": "https://archive.vn/2026.08.09-090750/https://www.youtube.com/watch?v=hxOO4D8pQQA",
        "stream_date_if_known": "27 Jul 2025",
        "participants": ["Neuro", "Vedal"],
        "language": "en",
        "subtitle_languages": [],
        "download_status": "pending",
        "processing_status": "pending",
        "rights_note": "Public archive lead; archive page is provenance evidence while media access must be verified independently.",
    },
    {
        "source_platform": "bilibili",
        "source_id": "BV12W8izqEUy",
        "source_url": "https://www.bilibili.com/video/BV12W8izqEUy/",
        "title": "Evil熟切：人间佳酿，共饮一杯！",
        "uploader": "于之鱼Fessy",
        "discovery_method": "public_web_search",
        "discovery_query": "Evil Neuro 熟肉 Bilibili 2025",
        "discovery_source": "https://www.bilibili.com/video/BV12W8izqEUy/",
        "stream_date_if_known": "25 Jul 2025",
        "participants": ["Evil", "Neuro"],
        "language": "zh-Hans",
        "subtitle_languages": ["zh-Hans"],
        "download_status": "pending",
        "processing_status": "pending",
        "training_candidate": False,
        "rights_note": "Public human-subtitle clip lead; preserve subtitle attribution and recover full source before high-weight training.",
    },
    {
        "source_platform": "bilibili",
        "source_id": "BV18QdCYpESb",
        "source_url": "https://www.bilibili.com/video/BV18QdCYpESb/",
        "title": "Evil/Neuro熟肉：全国兄弟姐妹日（合集索引）",
        "uploader": "Bilibili subtitle uploader (to verify)",
        "discovery_method": "public_web_search",
        "discovery_query": "Evil Neuro 熟肉 Bilibili 字幕组 合集",
        "discovery_source": "https://www.bilibili.com/video/BV18QdCYpESb/",
        "participants": ["Evil", "Neuro", "Vedal"],
        "language": "zh-Hans",
        "subtitle_languages": ["zh-Hans"],
        "download_status": "pending",
        "processing_status": "pending",
        "training_candidate": False,
        "rights_note": "Public subtitle compilation lead; retain for source recovery and reject isolated clip segments by default.",
    },
    {
        "source_platform": "bilibili",
        "source_id": "BV1DVoQY5EyJ",
        "source_url": "https://www.bilibili.com/video/BV1DVoQY5EyJ/",
        "title": "直播集锦：刺客信条影找Neuro带货真是捡到宝了",
        "uploader": "Bilibili uploader (to verify)",
        "discovery_method": "public_web_search",
        "discovery_query": "Neuro Evil Vedal 熟肉 Bilibili 长剪辑",
        "discovery_source": "https://www.bilibili.com/video/BV1DVoQY5EyJ/",
        "participants": ["Neuro", "Evil", "Vedal"],
        "language": "zh-Hans",
        "subtitle_languages": ["zh-Hans"],
        "download_status": "pending",
        "processing_status": "pending",
        "training_candidate": False,
        "rights_note": "Public compilation lead; use for locating original VOD and attributed subtitles, not as direct high-weight training.",
    },
    {
        "source_platform": "bilibili",
        "source_id": "BV1LaaCeXEH6",
        "source_url": "https://www.bilibili.com/video/BV1LaaCeXEH6/",
        "title": "Neuro-sama在B站首播开播的盛况",
        "uploader": "Bilibili uploader (to verify)",
        "discovery_method": "public_web_search",
        "discovery_query": "Neuro-sama Bilibili 首播 录播",
        "discovery_source": "https://www.bilibili.com/video/BV1LaaCeXEH6/",
        "participants": ["Neuro", "Vedal"],
        "language": "zh-Hans",
        "subtitle_languages": ["zh-Hans"],
        "download_status": "pending",
        "processing_status": "pending",
        "training_candidate": False,
        "rights_note": "Public historical clip/recording lead; verify completeness and preserve uploader/source attribution.",
    },
    {
        "source_platform": "bilibili",
        "source_id": "BV1oWjj6UEMd",
        "source_url": "https://www.bilibili.com/video/BV1oWjj6UEMd/",
        "title": "Neuro/Evil熟肉：妹妹互动与派对星相关对话合集",
        "uploader": "Bilibili subtitle uploader (to verify)",
        "discovery_method": "public_web_search",
        "discovery_query": "Neuro Evil 熟肉 Bilibili 2026",
        "discovery_source": "https://www.bilibili.com/video/BV1oWjj6UEMd/",
        "participants": ["Neuro", "Evil", "Vedal"],
        "language": "zh-Hans",
        "subtitle_languages": ["zh-Hans"],
        "download_status": "pending",
        "processing_status": "pending",
        "training_candidate": False,
        "rights_note": "Public human-subtitle compilation lead; retain attribution and recover original context before training use.",
    },
    {
        "source_platform": "bilibili",
        "source_id": "BV11L411r7DQ",
        "source_url": "https://www.bilibili.com/video/BV11L411r7DQ/",
        "title": "Neuro-sama切片合集：早期直播与开发互动线索",
        "uploader": "Bilibili uploader (to verify)",
        "discovery_method": "public_web_search",
        "discovery_query": "Neuro-sama Bilibili 切片合集 开发直播",
        "discovery_source": "https://www.bilibili.com/video/BV11L411r7DQ/",
        "participants": ["Neuro", "Vedal"],
        "language": "zh-Hans",
        "subtitle_languages": ["zh-Hans"],
        "download_status": "pending",
        "processing_status": "pending",
        "training_candidate": False,
        "rights_note": "Public compilation lead; preserve for source discovery, not direct high-weight training without context.",
    },
    {
        "source_platform": "bilibili",
        "source_id": "BV11r42147oq",
        "source_url": "https://www.bilibili.com/video/BV11r42147oq/",
        "title": "Neuro 3月18日录播：Neuro-sama Returns（粗校对机翻线索）",
        "uploader": "Bilibili subtitle/recording uploader (to verify)",
        "discovery_method": "public_web_search",
        "discovery_query": "Neuro 3月18日录播 Neuro-sama Returns Bilibili",
        "discovery_source": "https://www.bilibili.com/video/BV11r42147oq/",
        "stream_date_if_known": "18 Mar 2024",
        "participants": ["Neuro", "Vedal", "Evil"],
        "language": "zh-Hans",
        "subtitle_languages": ["zh-Hans"],
        "download_status": "pending",
        "processing_status": "pending",
        "training_candidate": False,
        "rights_note": "Public subtitle/recording lead; machine-translated subtitle quality must be preserved and separately assessed.",
    },
    {
        "source_platform": "bilibili",
        "source_id": "BV16LY1eKENj",
        "source_url": "https://www.bilibili.com/video/BV16LY1eKENj/",
        "title": "Evil 8月13日首次B站开发者直播（机翻未校对线索）",
        "uploader": "拿铁摩卡卡布奇诺",
        "discovery_method": "public_web_search",
        "discovery_query": "Evil 开发者直播 Bilibili 8月13日 Neuro",
        "discovery_source": "https://www.bilibili.com/video/BV16LY1eKENj/",
        "stream_date_if_known": "13 Aug 2024",
        "participants": ["Evil", "Neuro", "Vedal"],
        "language": "zh-Hans",
        "subtitle_languages": ["zh-Hans"],
        "download_status": "pending",
        "processing_status": "pending",
        "training_candidate": False,
        "rights_note": "Public recording/playlist lead with explicitly unproofread machine translation; preserve attribution and quality caveat.",
    },
    {
        "source_platform": "bilibili",
        "source_id": "BV17wyFYmEUV",
        "source_url": "https://www.bilibili.com/video/BV17wyFYmEUV/",
        "title": "2024年10月16日 Evil Neuro karaoke 录播线索",
        "uploader": "Bilibili recording uploader (to verify)",
        "discovery_method": "public_web_search",
        "discovery_query": "Evil Neuro karaoke 2024 录播 Bilibili",
        "discovery_source": "https://www.bilibili.com/video/BV17wyFYmEUV/",
        "stream_date_if_known": "16 Oct 2024",
        "participants": ["Evil", "Neuro", "Vedal"],
        "language": "en",
        "subtitle_languages": [],
        "download_status": "pending",
        "processing_status": "pending",
        "training_candidate": False,
        "rights_note": "Public recording lead; singing-heavy content is retained for archive completeness but low priority for dialogue training.",
    },
    {
        "source_platform": "bilibili",
        "source_id": "BV12tstzNEcQ",
        "source_url": "https://www.bilibili.com/video/BV12tstzNEcQ/",
        "title": "20251022 Neuro直播（两部分完整录像线索）",
        "uploader": "Bilibili recording uploader (to verify)",
        "discovery_method": "public_web_search",
        "discovery_query": "20251022 Neuro直播 Bilibili 完整录像",
        "discovery_source": "https://www.bilibili.com/video/BV12tstzNEcQ/",
        "stream_date_if_known": "22 Oct 2025",
        "participants": ["Neuro", "Evil", "Vedal"],
        "language": "en",
        "subtitle_languages": [],
        "download_status": "pending",
        "processing_status": "pending",
        "rights_note": "Public two-part recording lead; verify source completeness and attribution before training use.",
    },
    {
        "source_platform": "youtube",
        "source_id": "xE4jYz6jnYU",
        "source_url": "https://www.youtube.com/watch?v=xE4jYz6jnYU",
        "title": "Giving Evil Neuro ACCESS TO AMAZON",
        "uploader": "Neuro-sama",
        "discovery_method": "public_web_search",
        "discovery_query": "site:glasp.co/youtube Evil Neuro transcript",
        "discovery_source": "https://glasp.co/youtube/xE4jYz6jnYU",
        "participants": ["Neuro", "Evil", "Vedal"],
        "language": "en",
        "subtitle_languages": [],
        "download_status": "pending",
        "processing_status": "pending",
        "transcript_source": "Glasp public transcript index lead",
        "transcript_source_url": "https://glasp.co/youtube/xE4jYz6jnYU",
        "training_candidate": False,
        "rights_note": "Public transcript-index lead; verify original media and provenance before processing.",
    },
    {
        "source_platform": "youtube",
        "source_id": "NqyzbHF0E2o",
        "source_url": "https://www.youtube.com/watch?v=NqyzbHF0E2o",
        "title": "The AI Twins Explore Japan!",
        "uploader": "Neuro-sama",
        "discovery_method": "public_web_search",
        "discovery_query": "site:glasp.co/youtube Neuro-sama twins transcript",
        "discovery_source": "https://glasp.co/youtube/NqyzbHF0E2o",
        "participants": ["Neuro", "Evil", "Vedal"],
        "language": "en",
        "subtitle_languages": [],
        "download_status": "pending",
        "processing_status": "pending",
        "transcript_source": "Glasp public transcript index lead",
        "transcript_source_url": "https://glasp.co/youtube/NqyzbHF0E2o",
        "training_candidate": False,
        "rights_note": "Public transcript-index lead; verify original media and provenance before processing.",
    },
]

# Additional public Bilibili discovery leads recovered from independent web
# indexes. They remain explicitly low-priority/clip-quality until a parent VOD
# can be recovered; keeping them in the manifest preserves provenance without
# letting isolated memes dominate training selection.
LEADS.extend([
    {
        "source_platform": "bilibili",
        "source_id": "BV1TbH3zUEnu",
        "source_url": "https://www.bilibili.com/video/BV1TbH3zUEnu/",
        "title": "熟肉：Evil Neuro 向观众展示她的角（2025-10-03 clip）",
        "uploader": "凌渡LingAgo",
        "discovery_method": "public_web_search",
        "discovery_query": "Evil Neuro Bilibili 熟肉 2025-10-03",
        "discovery_source": "https://www.bilibili.com/video/BV1TbH3zUEnu/",
        "stream_date_if_known": "3 Oct 2025",
        "participants": ["Evil", "Neuro"],
        "language": "zh-Hans",
        "subtitle_languages": ["zh-Hans"],
        "download_status": "pending",
        "processing_status": "pending",
        "training_candidate": False,
        "rights_note": "Public subtitle clip lead; retain attribution and seek the parent VOD before training use.",
    },
    {
        "source_platform": "bilibili",
        "source_id": "BV151gh6uE5C",
        "source_url": "https://www.bilibili.com/video/BV151gh6uE5C/",
        "title": "Evil熟肉：粉丝画作鉴赏（2026-07-24 clip）",
        "uploader": "@E_Douraze",
        "discovery_method": "public_web_search",
        "discovery_query": "Evil Neuro Bilibili 粉丝画作 熟肉 2026-07-24",
        "discovery_source": "https://www.bilibili.com/video/BV151gh6uE5C/",
        "stream_date_if_known": "24 Jul 2026",
        "participants": ["Evil", "Neuro", "Vedal"],
        "language": "zh-Hans",
        "subtitle_languages": ["zh-Hans"],
        "download_status": "pending",
        "processing_status": "pending",
        "training_candidate": False,
        "rights_note": "Public translated clip lead; preserve translator/uploader attribution and parent-stream relationship.",
    },
    {
        "source_platform": "bilibili",
        "source_id": "BV17i4y1q7t1",
        "source_url": "https://www.bilibili.com/video/BV17i4y1q7t1/",
        "title": "Neuro 12月30日录播机翻片段（2023-12-30）",
        "uploader": "Bilibili machine-subtitle uploader (to verify)",
        "discovery_method": "public_web_search",
        "discovery_query": "Neuro-sama 12月30日录播 Bilibili 机翻",
        "discovery_source": "https://www.bilibili.com/video/BV17i4y1q7t1/",
        "stream_date_if_known": "30 Dec 2023",
        "participants": ["Neuro", "Vedal"],
        "language": "zh-Hans",
        "subtitle_languages": ["zh-Hans"],
        "download_status": "pending",
        "processing_status": "pending",
        "training_candidate": False,
        "rights_note": "Public machine-translated clip/collection lead; preserve raw text and do not treat it as ground truth.",
    },
    {
        "source_platform": "bilibili",
        "source_id": "BV1Zk4y147qt",
        "source_url": "https://www.bilibili.com/video/BV1Zk4y147qt/",
        "title": "Neuro-sama：双重人格对话，Evil Neuro 在线交流病情",
        "uploader": "阿鉴评测",
        "discovery_method": "public_web_search",
        "discovery_query": "Neuro-sama Evil Neuro 双重人格 对话 Bilibili",
        "discovery_source": "https://www.bilibili.com/video/BV1Zk4y147qt/",
        "stream_date_if_known": "26 Mar 2023",
        "participants": ["Neuro", "Evil"],
        "language": "zh-Hans",
        "subtitle_languages": ["zh-Hans"],
        "download_status": "pending",
        "processing_status": "pending",
        "training_candidate": False,
        "rights_note": "Public early dual-persona compilation lead; isolate parent stream and attribution before any model use.",
    },
    {
        "source_platform": "bilibili",
        "source_id": "BV1tL411i7nD",
        "source_url": "https://www.bilibili.com/video/BV1tL411i7nD/",
        "title": "后来邪恶Neuro：双AI趣味互动（2023-06-05）",
        "uploader": "Bilibili repost uploader (to verify)",
        "discovery_method": "public_web_search",
        "discovery_query": "Evil Neuro 双AI 2023 6月5日 Bilibili",
        "discovery_source": "https://www.bilibili.com/video/BV1tL411i7nD/",
        "stream_date_if_known": "5 Jun 2023",
        "participants": ["Neuro", "Evil", "Vedal"],
        "language": "zh-Hans",
        "subtitle_languages": ["zh-Hans"],
        "download_status": "pending",
        "processing_status": "pending",
        "training_candidate": False,
        "rights_note": "Public historical clip lead linked to a Twitch VOD in its description; parent-source recovery required.",
    },
    {
        "source_platform": "bilibili",
        "source_id": "BV1Ld4y1H7wL",
        "source_url": "https://www.bilibili.com/video/BV1Ld4y1H7wL/",
        "title": "Neuro-sama：人工智能在联动直播中拷打皮套人",
        "uploader": "Bilibili repost/subtitle uploader (to verify)",
        "discovery_method": "public_web_search",
        "discovery_query": "Neuro-sama 联动直播 Vedal Bilibili 熟肉",
        "discovery_source": "https://www.bilibili.com/video/BV1Ld4y1H7wL/",
        "participants": ["Neuro", "Vedal"],
        "language": "zh-Hans",
        "subtitle_languages": ["zh-Hans"],
        "download_status": "pending",
        "processing_status": "pending",
        "training_candidate": False,
        "rights_note": "Public collaboration clip lead; retain as source-recovery evidence, not direct high-weight training.",
    },
])


def update_json(path: Path, additions: list[dict]) -> int:
    current = json.loads(path.read_text(encoding="utf-8")) if path.exists() else {"frontier": []}
    existing = {str(x.get("url")) for x in current.get("frontier", [])}
    added = 0
    for item in additions:
        if item["url"] in existing:
            continue
        current.setdefault("frontier", []).append(item)
        existing.add(item["url"])
        added += 1
    current["updated_at"] = "2026-09-10"
    path.write_text(json.dumps(current, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return added


if __name__ == "__main__":
    rows = []
    for lead in LEADS:
        row = dict(lead)
        row["duplicate_group"] = None
        rows.append(row)
    write_master(merge_rows(read_jsonl(ROOT / "manifest" / "master_video_manifest.jsonl"), rows))

    registry_path = ROOT / "source_registry.json"
    registry = json.loads(registry_path.read_text(encoding="utf-8"))
    existing_ids = {str(x.get("source_id")) for x in registry.get("sources", [])}
    source_additions = [
        {"source_id": "web_archive_index_search", "platform": "web", "kind": "archive_index", "name": "Archive.vn Neuro Archiver snapshots", "url": "https://archive.vn/", "uploader": "archive index", "priority": "medium", "discovery_status": "seeded", "notes": "Use archived public pages as provenance leads; verify current media independently."},
        {"source_id": "bilibili_public_search_2026_09", "platform": "bilibili", "kind": "subtitle_and_clip_search", "name": "Bilibili public Neuro/Evil search leads", "url": "https://search.bilibili.com/all?keyword=Neuro-sama", "uploader": "various public uploaders", "priority": "high", "discovery_status": "expanded", "notes": "Human-subtitle and compilation leads; source recovery and attribution required."},
        {"source_id": "bilibili_neuro21_roast_group", "platform": "bilibili", "kind": "subtitle_group", "name": "Neuro21烤肉组", "url": "https://search.bilibili.com/all?keyword=Neuro21%E7%83%A4%E8%82%89%E7%BB%84", "uploader": "Neuro21烤肉组", "priority": "high", "discovery_status": "seeded_from_video_description", "notes": "Community subtitle/recording lead named in public Bilibili descriptions; exact space and permissions require verification."},
        {"source_id": "bilibili_niurou_roast_bar", "platform": "bilibili", "kind": "subtitle_group", "name": "牛肉烤吧", "url": "https://search.bilibili.com/all?keyword=%E7%89%9B%E8%82%89%E7%83%A4%E5%90%A7", "uploader": "牛肉烤吧", "priority": "high", "discovery_status": "seeded_from_video_description", "notes": "Publicly named subtitle/recording group; preserve attribution and find long-form source links."},
        {"source_id": "bilibili_ice_mocha_cappuccino", "platform": "bilibili", "kind": "recording_and_subtitle_uploader", "name": "拿铁摩卡卡布奇诺", "url": "https://search.bilibili.com/all?keyword=%E6%8B%BF%E9%93%81%E6%91%A9%E5%8D%A1%E5%8D%A1%E5%B8%83%E5%A5%87%E8%AF%BA", "uploader": "拿铁摩卡卡布奇诺", "priority": "high", "discovery_status": "seeded_from_video_search", "notes": "Public Bilibili recording/translation lead with early developer streams and machine-translation caveats."},
        {"source_id": "bilibili_nus_broadcast_committee", "platform": "bilibili", "kind": "weekly_news_and_recording_group", "name": "NeuS放送委员会", "url": "https://search.bilibili.com/all?keyword=NeuS%E6%94%BE%E9%80%81%E5%A7%94%E5%91%98%E4%BC%9A", "uploader": "NeuS放送委员会", "priority": "medium", "discovery_status": "seeded_from_video_search", "notes": "Weekly roundup links provide dates and source VOD IDs; roundup dialogue is not treated as original Neuro audio."},
        {"source_id": "yt_vedal_vods_archive", "platform": "youtube", "kind": "fan_fullstream_archive", "name": "Neuro-sama Stream Archive / vedalvods", "url": "https://www.youtube.com/channel/UCVlZAhUVWiUJt7DxwKpKG9w", "uploader": "Neuro-sama Stream Archive", "priority": "critical", "discovery_status": "discovered_from_web_search", "notes": "Publicly indexed unofficial VOD archive for vedal987; enumerate public uploads and deduplicate against official/fan archives."},
        {"source_id": "twitch_archive_twitchnosub_vedal987", "platform": "web", "kind": "twitch_vod_archive", "name": "TwitchNoSub vedal987 archive", "url": "https://twitchnosub.com/streamer/vedal987", "uploader": "TwitchNoSub", "priority": "high", "discovery_status": "discovered_from_web_search", "notes": "Public archive index lead for full VOD pages; verify media accessibility and provenance before acquisition."},
        {"source_id": "twitch_archive_streamrecorder_vedal987", "platform": "web", "kind": "twitch_vod_archive", "name": "StreamRecorder vedal987 archive", "url": "https://streamrecorder.io/twitch/vedal987", "uploader": "StreamRecorder", "priority": "high", "discovery_status": "discovered_from_web_search", "notes": "Public VOD-recording index lead; use as alternate source and preserve retrieval attribution."},
        {"source_id": "twitch_archive_vodarchive", "platform": "web", "kind": "twitch_vod_archive", "name": "VOD Archive", "url": "https://vodarchive.com/", "uploader": "VOD Archive", "priority": "medium", "discovery_status": "discovered_from_web_search", "notes": "General public VOD search index; query vedal987 only through normal public UI/API paths."},
        {"source_id": "twitch_vedal987_jp_archive_lead", "platform": "twitch", "kind": "related_channel", "name": "vedal987_jp", "url": "https://www.twitch.tv/vedal987_jp", "uploader": "vedal987_jp", "priority": "medium", "discovery_status": "discovered_from_web_search", "notes": "Related Japanese-language channel lead; enumerate only publicly accessible VOD/clip metadata."},
        {"source_id": "web_preservetube_neuro", "platform": "web", "kind": "channel_archive_index", "name": "PreserveTube Neuro-sama archive index", "url": "https://preservetube.com/channel/UCLHmLrj4pHHg3-iBJn_CqxA", "uploader": "PreserveTube", "priority": "high", "discovery_status": "discovered_from_web_search", "notes": "Public preservation index for Neuro-sama-related YouTube videos; use as metadata/provenance lead and deduplicate against direct media sources."},
    ]
    for item in source_additions:
        if item["source_id"] not in existing_ids:
            registry["sources"].append(item)
            existing_ids.add(item["source_id"])
    registry_path.write_text(json.dumps(registry, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    frontier_additions = [{"type": "video_lead", "platform": x["source_platform"], "url": x["source_url"], "status": "pending", "next_actions": ["verify public access", "capture metadata and attribution", "deduplicate against existing stream or clip"]} for x in LEADS]
    frontier_added = update_json(ROOT / "discovery_frontier.json", frontier_additions)
    print(json.dumps({"manifest_leads": len(LEADS), "frontier_added": frontier_added, "registry_added": len(source_additions)}, ensure_ascii=False))
